package br.univates.apresentacao;

import br.univates.easylibmanager.SistemaEasyLibManager;
import br.univates.system32.db.DataBaseException;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class TelaMenuPrincipal extends javax.swing.JFrame
{

    public TelaMenuPrincipal()
    {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle(SistemaEasyLibManager.getInstance().getApplicationName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuMovimentacoes = new javax.swing.JMenu();
        jMenuItemEmprestimo = new javax.swing.JMenuItem();
        jMenuItemDevolucao = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemCadastrarCliente = new javax.swing.JMenuItem();
        jMenuItemCadastrarLivro = new javax.swing.JMenuItem();
        jMenuItemCadastraUsuario = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuItemLivros = new javax.swing.JMenuItem();
        jMenuEditar = new javax.swing.JMenu();
        jMenuItemDefinicoes = new javax.swing.JMenuItem();
        jMenuRelatorioLivrosCategoria = new javax.swing.JMenu();
        jMenuItemListagemClientes = new javax.swing.JMenuItem();
        jMenuItemListagemAutores = new javax.swing.JMenuItem();
        jMenuItemRelatorioLivrosCategoria = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuMovimentacoes.setText("Movimentações");

        jMenuItemEmprestimo.setText("Empréstimo");
        jMenuItemEmprestimo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemEmprestimoActionPerformed(evt);
            }
        });
        jMenuMovimentacoes.add(jMenuItemEmprestimo);

        jMenuItemDevolucao.setText("Devolução");
        jMenuItemDevolucao.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemDevolucaoActionPerformed(evt);
            }
        });
        jMenuMovimentacoes.add(jMenuItemDevolucao);

        jMenuBar1.add(jMenuMovimentacoes);

        jMenu3.setText("Cadastros");

        jMenuItemCadastrarCliente.setText("Cliente");
        jMenuItemCadastrarCliente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemCadastrarClienteActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemCadastrarCliente);

        jMenuItemCadastrarLivro.setText("Livro");
        jMenuItemCadastrarLivro.setToolTipText("");
        jMenuItemCadastrarLivro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemCadastrarLivroActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemCadastrarLivro);

        jMenuItemCadastraUsuario.setText("Usuário");
        jMenuItemCadastraUsuario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemCadastraUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemCadastraUsuario);

        jMenuBar1.add(jMenu3);

        jMenuConsultas.setText("Consultas");

        jMenuItemLivros.setText("Livros");
        jMenuItemLivros.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemLivrosActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemLivros);

        jMenuBar1.add(jMenuConsultas);

        jMenuEditar.setText("Editar");

        jMenuItemDefinicoes.setText("Definições");
        jMenuItemDefinicoes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemDefinicoesActionPerformed(evt);
            }
        });
        jMenuEditar.add(jMenuItemDefinicoes);

        jMenuBar1.add(jMenuEditar);

        jMenuRelatorioLivrosCategoria.setText("Impressões");

        jMenuItemListagemClientes.setText("Listagem de Clientes");
        jMenuItemListagemClientes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemListagemClientesActionPerformed(evt);
            }
        });
        jMenuRelatorioLivrosCategoria.add(jMenuItemListagemClientes);

        jMenuItemListagemAutores.setText("Listagem de Autores");
        jMenuItemListagemAutores.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemListagemAutoresActionPerformed(evt);
            }
        });
        jMenuRelatorioLivrosCategoria.add(jMenuItemListagemAutores);

        jMenuItemRelatorioLivrosCategoria.setText("Relatório de Livros por Categoria");
        jMenuItemRelatorioLivrosCategoria.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemRelatorioLivrosCategoriaActionPerformed(evt);
            }
        });
        jMenuRelatorioLivrosCategoria.add(jMenuItemRelatorioLivrosCategoria);

        jMenuBar1.add(jMenuRelatorioLivrosCategoria);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 651, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadastraUsuarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemCadastraUsuarioActionPerformed
    {//GEN-HEADEREND:event_jMenuItemCadastraUsuarioActionPerformed
        new TelaCadastroUsuarios().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastraUsuarioActionPerformed

    private void jMenuItemCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemCadastrarClienteActionPerformed
    {//GEN-HEADEREND:event_jMenuItemCadastrarClienteActionPerformed
        new TelaCadastroClientes().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarClienteActionPerformed

    private void jMenuItemCadastrarLivroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemCadastrarLivroActionPerformed
    {//GEN-HEADEREND:event_jMenuItemCadastrarLivroActionPerformed
        new TelaCadastroLivros().setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarLivroActionPerformed

    private void jMenuItemListagemClientesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemListagemClientesActionPerformed
    {//GEN-HEADEREND:event_jMenuItemListagemClientesActionPerformed
        Connection connection = null;
        try
        {
            // Obtém a conexão com o banco de dados
            connection = SistemaEasyLibManager.getInstance().getDataBaseManager().getConnection();

            // Compilar o relatório do formato XML gerando um objeto JasperReport
            JasperReport report = JasperCompileManager.compileReport(getClass().getResourceAsStream("/br/univates/resources/reports/ListagemClientes.jrxml"));

            // Cria uma lista de parâmetros para o relatório
            Map param = new HashMap();

            // Gera o relatório efetivamente
            JasperPrint print = JasperFillManager.fillReport(report, param, connection);

            // Exibir o relatório
            JasperViewer.viewReport(print, false);
        } catch (DataBaseException | JRException ex)
        {
            Logger.getLogger(TelaMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemListagemClientesActionPerformed

    private void jMenuItemEmprestimoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemEmprestimoActionPerformed
    {//GEN-HEADEREND:event_jMenuItemEmprestimoActionPerformed
        new TelaEmprestimo().setVisible(true);
    }//GEN-LAST:event_jMenuItemEmprestimoActionPerformed

    private void jMenuItemDevolucaoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemDevolucaoActionPerformed
    {//GEN-HEADEREND:event_jMenuItemDevolucaoActionPerformed
        new TelaDevolução().setVisible(true);
    }//GEN-LAST:event_jMenuItemDevolucaoActionPerformed

    private void jMenuItemDefinicoesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemDefinicoesActionPerformed
    {//GEN-HEADEREND:event_jMenuItemDefinicoesActionPerformed
        new TelaDefinicoes().setVisible(true);
    }//GEN-LAST:event_jMenuItemDefinicoesActionPerformed

    private void jMenuItemLivrosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemLivrosActionPerformed
    {//GEN-HEADEREND:event_jMenuItemLivrosActionPerformed
        new TelaConsultaLivro().setVisible(true);
    }//GEN-LAST:event_jMenuItemLivrosActionPerformed

    private void jMenuItemRelatorioLivrosCategoriaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemRelatorioLivrosCategoriaActionPerformed
    {//GEN-HEADEREND:event_jMenuItemRelatorioLivrosCategoriaActionPerformed
        new TelaRelatorioLivrosCategoria().setVisible(true);
    }//GEN-LAST:event_jMenuItemRelatorioLivrosCategoriaActionPerformed

    private void jMenuItemListagemAutoresActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemListagemAutoresActionPerformed
    {//GEN-HEADEREND:event_jMenuItemListagemAutoresActionPerformed
        Connection connection = null;
        try
        {
            // Obtém a conexão com o banco de dados
            connection = SistemaEasyLibManager.getInstance().getDataBaseManager().getConnection();

            // Compilar o relatório do formato XML gerando um objeto JasperReport
            JasperReport report = JasperCompileManager.compileReport(getClass().getResourceAsStream("/br/univates/resources/reports/ListagemAutores.jrxml"));

            // Cria uma lista de parâmetros para o relatório
            Map param = new HashMap();

            // Gera o relatório efetivamente
            JasperPrint print = JasperFillManager.fillReport(report, param, connection);

            // Exibir o relatório
            JasperViewer.viewReport(print, false);
        } catch (DataBaseException | JRException ex)
        {
            Logger.getLogger(TelaMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemListagemAutoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new TelaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenuItem jMenuItemCadastraUsuario;
    private javax.swing.JMenuItem jMenuItemCadastrarCliente;
    private javax.swing.JMenuItem jMenuItemCadastrarLivro;
    private javax.swing.JMenuItem jMenuItemDefinicoes;
    private javax.swing.JMenuItem jMenuItemDevolucao;
    private javax.swing.JMenuItem jMenuItemEmprestimo;
    private javax.swing.JMenuItem jMenuItemListagemAutores;
    private javax.swing.JMenuItem jMenuItemListagemClientes;
    private javax.swing.JMenuItem jMenuItemLivros;
    private javax.swing.JMenuItem jMenuItemRelatorioLivrosCategoria;
    private javax.swing.JMenu jMenuMovimentacoes;
    private javax.swing.JMenu jMenuRelatorioLivrosCategoria;
    // End of variables declaration//GEN-END:variables
}
