/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.univates.system32.splash;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JProgressBar;

/**
 *
 * @author mouri
 */
public class SplashPanel extends javax.swing.JPanel {

    /**
     * Creates new form SplashPanel
     */
    public SplashPanel() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        imageLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        progressInfo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new java.awt.BorderLayout());

        imageLabel.setBackground(new java.awt.Color(255, 255, 255));
        add(imageLabel, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(progressBar, java.awt.BorderLayout.PAGE_START);

        progressInfo.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        progressInfo.setText(" Inicialização da aplicação...");
        jPanel1.add(progressInfo, java.awt.BorderLayout.PAGE_END);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents

    
    public void setImagePath( String imagePath )
    {
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource(imagePath ))); // NOI18N
    }

    public JProgressBar getProgressBar() {
        return progressBar;
    }

    public JLabel getProgressInfo()
    {
        return progressInfo;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel progressInfo;
    // End of variables declaration//GEN-END:variables
}
